language: node_js
node_js:
- '12'
services:
- docker
addons:
  ssh_known_hosts:
  - $IP
before_install: 
  - chmod 600 ~/.ssh/id_rsa  
  - npm install -g parcel-bundler
script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t muun/parcelhtml .
  - docker push muun/parcelhtml
after_success:
  - ssh root@$IP -o StrictHostKeyChecking=no 'docker-compose stop && docker-compose rm && docker-compose up -d'
