language: node_js
node_js:
  - '12'
services:
  - docker

before_install:
  # - npm install
  - npm install -g parcel-bundler

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t kelingm/parcelhtml .
  - docker push kelingm/parcelhtml