language: node_js
node_js:
- '12'
services:
- docker
addons:
  ssh_known_hosts:
  - "$IP"
before_install:
- openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- npm install -g parcel-bundler
script:
- npm run build
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t muun/parcelhtml .
- docker push muun/parcelhtml
after_success:
- ssh travis@$IP -o StrictHostKeyChecking=no 'cd ~/projects/parcelHtml && docker-compose pull && docker-compose stop -f && docker-compose rm -f && docker-compose up -d'
